# Generated by Django 2.1 on 2018-08-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCPapp', '0002_familia_escuela'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='calle',
            field=models.CharField(default='Nada', max_length=30),
        ),
        migrations.AddField(
            model_name='familia',
            name='colonia',
            field=models.CharField(default='Nada', max_length=30),
        ),
        migrations.AddField(
            model_name='familia',
            name='cp',
            field=models.CharField(default='Nada', max_length=30),
        ),
        migrations.AddField(
            model_name='familia',
            name='numero',
            field=models.CharField(default='Nada', max_length=30),
        ),
        migrations.AddField(
            model_name='familia',
            name='pasajeros',
            field=models.CharField(default='Nada', max_length=30),
        ),
    ]
