# Generated by Django 2.1 on 2018-08-26 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SCPapp', '0003_auto_20180826_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_recibe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_recibe', to='SCPapp.Familia')),
                ('usuario_sol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_sol', to='SCPapp.Familia')),
            ],
        ),
    ]
