# Generated by Django 2.1 on 2018-08-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCPapp', '0004_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='ocupantes',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='familia',
            name='pasajeros',
            field=models.IntegerField(default=3),
        ),
    ]
