# Generated by Django 2.1 on 2018-08-26 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SCPapp', '0005_auto_20180826_0254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_acomodado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_acomodado', to='SCPapp.Familia')),
                ('usuario_auto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_auto', to='SCPapp.Familia')),
            ],
        ),
    ]
