# Generated by Django 2.1 on 2018-08-26 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SCPapp', '0006_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_denegado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_denegado', to='SCPapp.Familia')),
                ('usuario_denego', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_denego', to='SCPapp.Familia')),
            ],
        ),
    ]
