# Generated by Django 2.1 on 2018-08-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCPapp', '0007_nomatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
