# Generated by Django 2.1 on 2018-08-26 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SCPapp', '0008_auto_20180826_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunes', models.CharField(max_length=20)),
                ('martes', models.CharField(max_length=20)),
                ('miercoles', models.CharField(max_length=20)),
                ('jueves', models.CharField(max_length=20)),
                ('viernes', models.CharField(max_length=20)),
                ('usuario_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_1', to='SCPapp.Familia')),
                ('usuario_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_2', to='SCPapp.Familia')),
            ],
        ),
    ]
