# Generated by Django 2.1 on 2018-08-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCPapp', '0009_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='jueves',
            field=models.CharField(default='hola', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='lunes',
            field=models.CharField(default='hola', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='martes',
            field=models.CharField(default='hola', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='miercoles',
            field=models.CharField(default='hola', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='viernes',
            field=models.CharField(default='hola', max_length=20),
        ),
    ]
